### ISSUE TITLE
No modification options. 

### ISSUE THREAD

**Issue by ReneFroger** [Fanael/rainbow-delimiters#10]
Hi there!

Thanks for the useful plugin. However, I'm running into some issues. 

Spec: I have Windows 7 x64, I installed Emacs 25 from [here](emacsbinw64.sourceforge.net). 

I installed rainbow-delimiters from MELPA, 20141221.925. 

Only when I enabled it manually from M-x, the rainbow delimiters are visible. When I would like to modify the colors, I try 'M-x customize-group'. But only rainbow is available, which is other plugin, I guess. There is no rainbow-delimiters available in customize-group. 

How could I debug this? 

Thanks in advance!

**Comment by Fanael** [comment]
`rainbow-delimiters` must be loaded, otherwise Emacs has no idea about the customization group. What does `(featurep 'rainbow-delimiters)` evaluate to?

**Comment by ReneFroger** [comment]
I typed `(featurep 'rainbow-delimiters)` and after that sentence, I pressed `C-x C-e`. I got `t` in the mini-buffer.

**Comment by Fanael** [comment]
Fine. What happens if you evaluate `(customize-group 'rainbow-delimiters)`?

**Comment by ReneFroger** [comment]
Then there is a buffer opened when I evaluate it. 

But it seems something is missing? 

![schermafdruk 2015-01-08 20 28 31](https://cloud.githubusercontent.com/assets/5211845/5669083/f8963562-9774-11e4-963c-3b38c5830f4e.png)

**Comment by Fanael** [comment]
And if you kill this buffer and try to `M-x customize-group RET rainbow-delimiters RET` again?

**Comment by ReneFroger** [comment]
I evaluated your previous sentence, killed the buffer, and it's still not available/visible in the `customize-group`.

**Comment by Fanael** [comment]
Weird, it works here.

Does the `rainbow-delimiters` group show up if you start a clean Emacs, eval `(require 'rainbow-delimiters)` and *then* call `customize-group`?

**Comment by ReneFroger** [comment]
Then it worked. So something weird is going on with my Emacs. I will figure it out once. 

Thanks for helping by the way!
