### ISSUE TITLE
Old version in marmelade

### ISSUE THREAD

**Issue by Knusper** [Fanael/rainbow-delimiters#11]
In the marmalade version an old version of this mode is lurking. It should be either removed there or updated with the newest version.

https://marmalade-repo.org/packages/rainbow-delimiters

**Comment by Fanael** [comment]
Please take this up with whoever put that there or with Marmalade maintainers. I don't use Marmalade and I don't support it, and this is one of the reasons why: `rainbow-delimiters` 1.3.21 [never even existed](https://github.com/Fanael/rainbow-delimiters/releases), the last 1.3.x version is 1.3.13; on top of that, this 1.3.21 looks like 1.3.2.

**Comment by purcell** [comment]
With the current version of Marmalade, it also doesn't appear possible to see who owns the package: only that person, or a newly-verified owner, would be able to update it there.
