### ISSUE TITLE
Disable rainbow delimiters for brackets only?

### ISSUE THREAD

**Issue by ReneFroger** [Fanael/rainbow-delimiters#12]
Hi there!

Here I'm again. 

I would like to have rainbow delimiters set off for brackets (I found them distracting in PHP-mode, the brackets are clearly enough for me thanks to the indentation). When I look into `M-x customize-group` for rainbow-delimiters, I found no settings to disable rainbow-delimiters for only brackets (so that parentheses will be only colorored). 

Any suggestions? Thanks in advance!

**Comment by Fanael** [comment]
See `rainbow-delimiters-pick-face-function`. For example:
```emacs-lisp
(defun foo (depth match loc)
  (if (memq (char-after loc) '(?\( ?\)))
      nil
    (rainbow-delimiters-default-pick-face depth match loc)))

(setq rainbow-delimiters-pick-face-function #'foo)
```

**Comment by ReneFroger** [comment]
Thanks for your reply!
