### ISSUE TITLE
orgmode code blocks?

### ISSUE THREAD

**Issue by zeltak** [Fanael/rainbow-delimiters#18]
Hi!

just found out about rainbow-delimiters and its great!

one Q though, it dosent seem to work in org mode lisp code blocks. any plans to support that in the future?

best

Z

**Comment by Fanael** [comment]
Works for me. How are you enabling rainbow-delimiters?

**Comment by zeltak** [comment]
Hi again

thx for the answer, i updated orgmode and it seems to work now :)

thx!

Z
