### ISSUE TITLE
Wrong unmatched braces highlighting in web-mode

### ISSUE THREAD

**Issue by mbme** [Fanael/rainbow-delimiters#19]
This code uses double quotes and its highlighting is ok:
```javascript
console.log(")");
```
This code uses single quotes and last brace is highlighted as unmatched:
```javascript
console.log(')');
```
Everything is ok when I use js-mode.

So probably rainbow-delimiters mode use some information provided by current major mode to detect if brace is inside string or not.

Reported this bug in web mode https://github.com/fxbois/web-mode/issues/584, but maybe @Fanael you have some suggestions what can be broken there?

**Comment by Fanael** [comment]
The highlighting is correct: in the first case the `)` is inside a string, so it's ignored by rainbow-delimiters, in the second case it's not. Or at least, that's what `web-mode` tells Emacs.

A solution is to fix `web-mode` to mark (as in, give them appropriate syntax-table entries or text properties) string delimiters as string delimiters.

**Comment by mbme** [comment]
thanks, hope this helps!

**Comment by fxbois** [comment]
@mbme does the patch just pushed change anything ?
