### ISSUE TITLE
Doesn't seem to work until after running cider-jack-in

### ISSUE THREAD

**Issue by losingkeys** [Fanael/rainbow-delimiters#21]
I've reduced my emacs to have the following packages:
- cider
- clojure-mode
- color-theme-solarized
- paredit 
- rainbow-delimiters

I've also blown away `~/.emacs.d/` and re-downloaded these packages.

Here's [a demo](https://asciinema.org/a/allvq9du5q9fpnr46d2xn3kiq) of the bug.

Happy to help debug! Just unsure about where to go from here. I couldn't find any "rainbow" specific code in clojure-mode or cider.

**Comment by Fanael** [comment]
Sounds like color-theme-solarized issue, as I was unable to reproduce the bug with any other problem.

**Comment by losingkeys** [comment]
You were right (https://github.com/sellout/emacs-color-theme-solarized/issues/165), thanks for pointing me in the right direction!
