### ISSUE TITLE
Problem with Mathematica comments

### ISSUE THREAD

**Issue by lecopivo** [Fanael/rainbow-delimiters#22]
I have a problem with comments in Wolfram Mathematica code. Comments are done like `(* comment *)` and those brackets are confusing `rainbow-delimiters`.

Example of broken behaviour
![mathematicarainbowproblem](https://cloud.githubusercontent.com/assets/6596305/15430273/def860ea-1ea4-11e6-8958-d163d0673fff.png)

**Comment by Fanael** [comment]
What major mode is that? Is it `wolfram-mode`? If it is, what version of rainbow-delimiters do you have installed? I can't reproduce with the current version.

**Comment by lecopivo** [comment]
Yes I'm using `wolfram-mode` , and I just realized that the problem is in the `wolfram-mode` not in `rainbow-delimiters`, sorry for that.

So this is a non issue.
