### ISSUE TITLE
parentheses all turn red when format codes

### ISSUE THREAD

**Issue by liuchong** [Fanael/rainbow-delimiters#25]
https://github.com/syl20bnr/spacemacs/issues/6617
https://github.com/rust-lang/rust-mode/issues/160

please refre to the above issue about rust layer in spacemacs, what I found is that after I format codes, the parentheses will turn red like this:
![parenthese_turn_red](https://cloud.githubusercontent.com/assets/236058/16915784/09807e1e-4d2c-11e6-96a3-c252622bdaa5.png)
So, is it a rainbow-delimiters issue? thanks!

**Comment by Fanael** [comment]
Can you provide some example code I can reproduce this on?

---

> on the other hand, when I use my own configuration without spacemacs, just "racer, ac-racer, company-racer, toml-mode", there is no such issue.

Uhh… if that's really true, it's probably a spacemacs issue then.

**Comment by Fanael** [comment]
It's a rust-mode bug as described in https://github.com/syl20bnr/spacemacs/issues/6617#issuecomment-233748418.

**Comment by liuchong** [comment]
Thanks!
