### ISSUE TITLE
I want to call rainbow-mode with another syntax table

### ISSUE THREAD

**Issue by raoulhatterer** [Fanael/rainbow-delimiters#33]
Hello
I want use rainbow-mode in a major mode I'm tempting to write. This mode is derived from sgml-mode. 
I called you mode that way:
`;;
(require 'rainbow-mode) 
(add-hook 'sgml-mode-hook 'oef-mode-hook) 
(defun oef-mode-hook ()
  (setq rainbow-html-colors t)
  (rainbow-mode 1)
  (rainbow-delimiters-mode 1)
  )
`
Because of comparison signs I removed < and > to get oef-mode-syntax table:

`(defvar oef-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?< "_" table)  ;Symbol constituent
    (modify-syntax-entry ?> "_" table)  ;Symbol constituent
    table)
  "oef Syntax Table")
`
Without removing <> as SGML matching parenthesis from the syntax table
oef-mode is not mattching parenthesis well when there is a comparison.
The problem is that the rest of the code work better wit sgml-make-syntax-table

Because of that I have to call fonctions with sgml-syntax-table.
For example:
`(defun oef-mode-indent-region (start end)
  (interactive (if (use-region-p)
                   (list (region-beginning) (region-end))
                 ;; Operate on the current line if region is not to be used.
                 (list (line-beginning-position) (line-end-position))))
  (with-syntax-table sgml-mode-syntax-table
    (indent-region start end)
    ))
`
Now I have problems with emmet-mode so a better way would be to have only rainbow-mode working with oef-mode-syntax table (a sgml-syntax table without < and >) and keeping sgml-syntax-table active for oef-mode.

I wonderer if what I'm asking is possible.
Sorry for my bad English (I'm french)

**Comment by Fanael** [comment]
Wrong bugtracker. You're looking for rainbow-mode, which is separate package unrelated to rainbow-delimiters.

**Comment by raoulhatterer** [comment]
You're right. Sorry for my message.
