### ISSUE TITLE
Make rainbow mode not match delimiters that are invisible

### ISSUE THREAD

**Issue by amosbird** [Fanael/rainbow-delimiters#34]
When editing large code blocks, there are delimiter pairs not shown in the same screen. Can I make rainbow mode stop matching those pairs. It's extremely slow.

**Comment by Fanael** [comment]
> Can I make rainbow mode stop matching those pairs.

That would essentially require #1.

> It's extremely slow.

Can you provide some example code I could test that on? In practice, it's very unusual for rainbow-delimiters to be *the* performance problem. What version are you using?

**Comment by amosbird** [comment]
Hmm, after some days of testing, it turns out not to be a rainbow mode's issue. Thanks :)
