### ISSUE TITLE
Proposal / advice needed: use background color to visualize expression depth instead of delimiters text color

### ISSUE THREAD

**Issue by idrozd** [Fanael/rainbow-delimiters#38]
Hello and thank you for your work!

I want to experiment implement following feature basing on rainbow-delimiters: 
use background colour lightness gradation to visualise expression depth instead of delimiters text colour.

I have no elisp experience.

Can you give some advise on this topics: 
Is is possible?
What elisp manual would you recommend?
What do I need to understand to make this work?

**Comment by Fanael** [comment]
You can just set the [`:background` property](https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html) on the respective faces by using [`set-face-attribute`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Attribute-Functions.html) or a custom theme.
