### ISSUE TITLE
Doesn't work in SLIME's REPL?

### ISSUE THREAD

**Issue by Ambrevar** [Fanael/rainbow-delimiters#39]
Enabling `rainbow-delimiters-mode` in SLIME's REPL does not do anything.
Any clue?

**Comment by Ambrevar** [comment]
Update: I realized that SLIME does something funky with font-lock-mode, thing which might conflict with what rainbow-delimiters-mode does.
If I disable font-lock-mode, enable rainbow-delimiters-mode, then re-enable font-lock-mode, it works.

Workaround in code:

```elisp
(defun slime-rainbow-init ()
  (font-lock-mode -1)
  (rainbow-delimiters-mode)
  (font-lock-mode))
(add-hook 'slime-repl-mode-hook #'slime-rainbow-init)
```

**Comment by Fanael** [comment]
This honestly makes it sound like a SLIME repl problem that would break interoperability with other font-lock extensions, not just rainbow-delimiters — rainbow-delimiters is just the messenger here, it doesn't do any significant font-lock hackery, it just uses well-documented `font-lock-add-keywords` to install its own highlighting; as such, it's probably best to report this issue to SLIME instead.

**Comment by Ambrevar** [comment]
Thanks, reported upstream.
