### ISSUE TITLE
doesn't highlight in evil-mode normal state

### ISSUE THREAD

**Issue by jsomedon** [Fanael/rainbow-delimiters#40]
My emacs buffer is configured to launch with evil mode's  normal state. Upon launching a buffer, no delimiters are highlighted at all. However, once I switch to evil's insertion state, delimiter highlighting works as expected.

**Comment by Fanael** [comment]
I can't reproduce it here, I use evil and it works fine for me. Could you try bisecting your config to find the problematic package or setting?

**Comment by jsomedon** [comment]
It was my solarized theme. Tried other themes and all worked fine.

I am closing this issue..
