### ISSUE TITLE
Is it possible to support highlight matching single quote, double quote?

### ISSUE THREAD

**Issue by taquangtrung** [Fanael/rainbow-delimiters#49]
Hi,

I really this package which helped me a lot to spot the matching parentheses.

I wonder if it can be extended to highlight the matching quote, like in the strings "aaa", or 'aaa'?
It will be very helpful for text-mode, org-mode, or markdown-mode to spot the missing quote in necessary cases.

Thanks for spending time taking a look at my issue.

**Comment by Fanael** [comment]
It should be possible to do that by [adding appropriate `syntax-table` properties](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Properties.html#Syntax-Properties) to the quote and apostrophe characters as needed, as `rainbow-delimiters` is pretty language agnostic and just looks at character classes internally. The properties of syntax are usually set up by the major mode, so this is outside the purview of `rainbow-delimiters`; you should look into [deriving your own major mode](https://www.gnu.org/software/emacs/manual/html_node/elisp/Derived-Modes.html) from `text-mode` etc.

**Comment by taquangtrung** [comment]
Thank you for the suggestion!
