### ISSUE TITLE
Mismatched Pairs in Org Table Formula

### ISSUE THREAD

**Issue by soberpeach** [Fanael/rainbow-delimiters#50]
Delimeters in the `#+TBLFM:` formula viewer are marked as unmatched pairs.

![unmatchedPairs](https://user-images.githubusercontent.com/36653792/87888019-9dcc4c80-c9ef-11ea-902d-6996c0c626a9.png)

Org version: 9.3.6
Emacs version: 28.0.50

**Comment by Fanael** [comment]
`org-mode` incorrectly marks the `>` character as being a closing angle bracket when it's not, thus confusing `rainbow-delimiters` and all other code using the built in syntax properties, such as *any* code that uses `parse-partial-sexp` or `syntax-ppss`. Needs to be fixed in `org-mode`.
