### ISSUE TITLE
Customize highlighted delimiters (in Org files)

### ISSUE THREAD

**Issue by scolobb** [Fanael/rainbow-delimiters#53]
After an Emacs update, I realized that rainbow-delimiters started to highlight `<` and `>`.  When I am writing math, this is rather inconvenient, because something like `k > 1` highlights the `>` and all the following delimiters as mismatched.

Is there a way to customize which delimiters are highlighted?

**Comment by scolobb** [comment]
I have just realized that this behavior seems to be specific to Org files.  The characters `<` and `>` are not highlighted in text mode, Lisp interaction mode, Racket mode, etc.
![2020-08-31_23-40](https://user-images.githubusercontent.com/11320/91771520-69999d80-ebe3-11ea-9ae7-00f017a928d3.png)

**Comment by Fanael** [comment]
`rainbow-delimiters` relies solely on the syntax table information provided by the major mode. If `org-mode` incorrectly sets `<` and `>` as a bracket pair even when they're not, it's a bug in `org-mode` and should be fixed there, especially since it has the potential to break *any code* that uses syntax information directly or indirectly (e.g. through `syntax-ppss`).

**Comment by scolobb** [comment]
Thank you @Fanael for the quick and detailed answer.  I'll contact the maintainers of Org-mode.

One last question: when you say "Org-mode sets `<` and `>` as a bracket pair", do you mean that there is some variable which lists the bracket pairs?  From the rest of your answer I understand that this is not so simple, but I would like to have a confirmation of my hypothesis.

**Comment by Fanael** [comment]
It's controlled by syntax tables and syntax properties: https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html

**Comment by scolobb** [comment]
Thank you @Fanael ! This part of the manual is what I needed, but didn't have the keywords.
