### ISSUE TITLE
How to make rainbow-delimiters work in emacs-shell?

### ISSUE THREAD

**Issue by taquangtrung** [Fanael/rainbow-delimiters#54]
Hi,

Recently, I switched from using `shell` to `eshell` and realized that `rainbow-deliminters` doesn't work in `eshell`: the parentheses are not highlighted (it works fine with `shell`).

Do you know how to fix this problem? 

Thank you!

**Comment by Fanael** [comment]
`eshell` is doing something weird with `font-lock-mode`, because re-enabling `font-lock-mode` after enabling `rainbow-delimiters-mode` fixes the problem for me.

**Comment by taquangtrung** [comment]
Thank you for the update. I found out that re-enabling `font-lock-mode` breaks the highlight color of `eshell` as well... Perhaps this is `eshell`'s problem.
