### ISSUE TITLE
issues compiling instalation

### ISSUE THREAD

**Issue by RedJocker** [Fanael/rainbow-delimiters#55]
I'm having problems during install, this is what shows up:

> Compiling file /Users/redjocker/.emacs.d/elpa/rainbow-delimiters-20200827.321/rainbow-delimiters.el at Thu Sep 10 15:21:09 2020
Entering directory ‘/Users/redjocker/.emacs.d/elpa/rainbow-delimiters-20200827.321/’
rainbow-delimiters.el:1:1:Warning: reference to free variable ‘<!DOCTYPE’
rainbow-delimiters.el:1:11:Warning: reference to free variable ‘html>’
rainbow-delimiters.el:2:1:Warning: reference to free variable ‘<html’
rainbow-delimiters.el:2:7:Warning: reference to free variable ‘lang=’
rainbow-delimiters.el:2:19:Warning: reference to free variable ‘>’
rainbow-delimiters.el:3:1:Warning: reference to free variable ‘<head>’
rainbow-delimiters.el:4:3:Warning: reference to free variable ‘<meta’
rainbow-delimiters.el:4:9:Warning: reference to free variable ‘http-equiv=’
rainbow-delimiters.el:4:35:Warning: reference to free variable ‘content=’
rainbow-delimiters.el:5:3:Warning: reference to free variable
    ‘<title>MELPA</title>’
rainbow-delimiters.el:6:9:Warning: reference to free variable ‘name=’
rainbow-delimiters.el:8:3:Warning: reference to free variable ‘<link’
rainbow-delimiters.el:8:9:Warning: reference to free variable ‘rel=’
rainbow-delimiters.el:8:29:Warning: reference to free variable ‘href=’
rainbow-delimiters.el:9:22:Warning: reference to free variable ‘type=’
rainbow-delimiters.el:9:90:Warning: reference to free variable ‘title=’
rainbow-delimiters.el:11:3:Warning: reference to free variable ‘’
rainbow-delimiters.el:14:1:Warning: reference to free variable ‘</head>’
rainbow-delimiters.el:15:1:Warning: reference to free variable ‘<body>’
rainbow-delimiters.el:16:3:Warning: reference to free variable ‘<header’
rainbow-delimiters.el:16:11:Warning: reference to free variable ‘class=’
rainbow-delimiters.el:17:5:Warning: reference to free variable ‘<div’
rainbow-delimiters.el:19:9:Warning: reference to free variable ‘<a’
rainbow-delimiters.el:19:55:Warning: reference to free variable ‘>MELPA</a>’
rainbow-delimiters.el:20:7:Warning: reference to free variable ‘</div>’
rainbow-delimiters.el:21:7:Warning: reference to free variable ‘<nav’
rainbow-delimiters.el:22:9:Warning: reference to free variable ‘<ul’
rainbow-delimiters.el:23:11:Warning: reference to free variable ‘<li><a’
rainbow-delimiters.el:23:27:Warning: reference to free variable
    ‘>Packages</a></li>’
rainbow-delimiters.el:24:42:Warning: reference to free variable ‘>Getting’
rainbow-delimiters.el:24:51:Warning: reference to free variable
    ‘started</a></li>’
rainbow-delimiters.el:25:55:Warning: reference to free variable
    ‘>GitHub</a></li>’
rainbow-delimiters.el:26:9:Warning: reference to free variable ‘</ul>’
rainbow-delimiters.el:28:49:Warning: reference to free variable ‘></a></li>’
rainbow-delimiters.el:30:7:Warning: reference to free variable ‘</nav>’
rainbow-delimiters.el:32:3:Warning: reference to free variable ‘</header>’
rainbow-delimiters.el:33:3:Warning: reference to free variable ‘<main’
rainbow-delimiters.el:33:27:Warning: reference to free variable ‘id=’
rainbow-delimiters.el:34:5:Warning: reference to free variable ‘<noscript>’
rainbow-delimiters.el:35:7:Warning: reference to free variable ‘<h1><span’
rainbow-delimiters.el:35:37:Warning: reference to free variable
    ‘>MELPA</span>’
rainbow-delimiters.el:35:67:Warning: reference to free variable ‘Emacs’
rainbow-delimiters.el:35:73:Warning: reference to free variable ‘Lisp’
rainbow-delimiters.el:35:78:Warning: reference to free variable ‘Package’
rainbow-delimiters.el:35:86:Warning: reference to free variable ‘Archive’
rainbow-delimiters.el:35:94:Warning: reference to free variable ‘</h1>’
rainbow-delimiters.el:36:7:Warning: reference to free variable ‘<ul>’
rainbow-delimiters.el:37:9:Warning: reference to free variable
    ‘<li><strong>Up-to-date’
rainbow-delimiters.el:37:32:Warning: reference to free variable ‘packages’
rainbow-delimiters.el:37:41:Warning: reference to free variable ‘built’
rainbow-delimiters.el:37:47:Warning: reference to free variable ‘on’
rainbow-delimiters.el:37:50:Warning: reference to free variable ‘our’
rainbow-delimiters.el:37:54:Warning: reference to free variable ‘servers’
rainbow-delimiters.el:37:62:Warning: reference to free variable ‘from’
rainbow-delimiters.el:37:67:Warning: reference to free variable ‘upstream’
rainbow-delimiters.el:37:76:Warning: reference to free variable
    ‘source</strong></li>’
rainbow-delimiters.el:38:9:Warning: reference to free variable
    ‘<li><strong>Installable’
rainbow-delimiters.el:38:33:Warning: reference to free variable ‘in’
rainbow-delimiters.el:38:36:Warning: reference to free variable ‘any’
rainbow-delimiters.el:38:46:Warning: reference to free variable ‘with’
rainbow-delimiters.el:38:73:Warning: reference to free variable ‘-’
rainbow-delimiters.el:38:75:Warning: reference to free variable ‘no’
rainbow-delimiters.el:38:78:Warning: reference to free variable ‘local’
rainbow-delimiters.el:38:100:Warning: reference to free variable ‘tools’
rainbow-delimiters.el:38:106:Warning: reference to free variable ‘needed</li>’
rainbow-delimiters.el:39:9:Warning: reference to free variable
    ‘<li><strong>Curated</strong>’
rainbow-delimiters.el:39:43:Warning: reference to free variable ‘obsolete’
rainbow-delimiters.el:39:53:Warning: reference to free variable ‘renamed’
rainbow-delimiters.el:39:62:Warning: reference to free variable ‘forked’
rainbow-delimiters.el:39:69:Warning: reference to free variable ‘or’
rainbow-delimiters.el:39:72:Warning: reference to free variable ‘randomly’
rainbow-delimiters.el:39:81:Warning: reference to free variable ‘hacked’
rainbow-delimiters.el:39:88:Warning: reference to free variable
    ‘packages</li>’
rainbow-delimiters.el:40:9:Warning: reference to free variable
    ‘<li><strong>Comprehensive</strong>’
rainbow-delimiters.el:40:46:Warning: reference to free variable ‘more’
rainbow-delimiters.el:40:60:Warning: reference to free variable ‘than’
rainbow-delimiters.el:40:69:Warning: reference to free variable ‘other’
rainbow-delimiters.el:40:75:Warning: reference to free variable ‘archive</li>’
rainbow-delimiters.el:41:9:Warning: reference to free variable
    ‘<li><strong>Automatic’
rainbow-delimiters.el:41:31:Warning: reference to free variable
    ‘updates</strong>’
rainbow-delimiters.el:41:50:Warning: reference to free variable ‘new’
rainbow-delimiters.el:41:54:Warning: reference to free variable ‘commits’
rainbow-delimiters.el:41:62:Warning: reference to free variable ‘result’
rainbow-delimiters.el:42:9:Warning: reference to free variable
    ‘<li><strong>Extensible</strong>’
rainbow-delimiters.el:42:43:Warning: reference to free variable ‘contribute’
rainbow-delimiters.el:42:54:Warning: reference to free variable ‘recipes’
rainbow-delimiters.el:42:62:Warning: reference to free variable ‘via’
rainbow-delimiters.el:42:66:Warning: reference to free variable ‘github’
rainbow-delimiters.el:42:74:Warning: reference to free variable ‘and’
rainbow-delimiters.el:42:78:Warning: reference to free variable ‘we’
rainbow-delimiters.el:42:84:Warning: reference to free variable ‘build’
rainbow-delimiters.el:42:90:Warning: reference to free variable ‘the’
rainbow-delimiters.el:44:7:Warning: reference to free variable ‘<p>This’
rainbow-delimiters.el:44:15:Warning: reference to free variable ‘site’
rainbow-delimiters.el:44:20:Warning: reference to free variable ‘requires’
rainbow-delimiters.el:44:29:Warning: reference to free variable ‘JavaScript’
rainbow-delimiters.el:44:40:Warning: reference to free variable ‘to’
rainbow-delimiters.el:44:43:Warning: reference to free variable ‘function\.’
rainbow-delimiters.el:44:53:Warning: reference to free variable ‘You’
rainbow-delimiters.el:44:57:Warning: reference to free variable ‘can’
rainbow-delimiters.el:44:61:Warning: reference to free variable ‘browse’
rainbow-delimiters.el:44:72:Warning: reference to free variable ‘install’
rainbow-delimiters.el:44:89:Warning: reference to free variable ‘directly’
rainbow-delimiters.el:44:172:Warning: reference to free variable ‘>see’
rainbow-delimiters.el:44:177:Warning: reference to free variable ‘MELPA’
rainbow-delimiters.el:44:185:Warning: reference to free variable ‘README\.md’
rainbow-delimiters.el:44:198:Warning: reference to free variable ‘GitHub</a>’
rainbow-delimiters.el:44:209:Warning: reference to free variable ‘\.</p>’
rainbow-delimiters.el:45:5:Warning: reference to free variable ‘</noscript>’
rainbow-delimiters.el:46:3:Warning: reference to free variable ‘</main>’
rainbow-delimiters.el:47:3:Warning: reference to free variable ‘<footer’
rainbow-delimiters.el:48:5:Warning: reference to free variable ‘<small>’
rainbow-delimiters.el:49:76:Warning: reference to free variable ‘>Source’
rainbow-delimiters.el:49:84:Warning: reference to free variable ‘code’
rainbow-delimiters.el:49:89:Warning: reference to free variable ‘for’
rainbow-delimiters.el:49:93:Warning: reference to free variable ‘this’
rainbow-delimiters.el:49:98:Warning: reference to free variable ‘page’
rainbow-delimiters.el:49:103:Warning: reference to free variable ‘&rarr’
rainbow-delimiters.el:50:7:Warning: reference to free variable ‘<br/>’
rainbow-delimiters.el:51:32:Warning: reference to free variable
    ‘data-jslicense=’
rainbow-delimiters.el:51:50:Warning: reference to free variable ‘>JavaScript’
rainbow-delimiters.el:51:62:Warning: reference to free variable ‘license’
rainbow-delimiters.el:51:70:Warning: reference to free variable
    ‘information</a>’
rainbow-delimiters.el:52:5:Warning: reference to free variable ‘</small>’
rainbow-delimiters.el:53:3:Warning: reference to free variable ‘</footer>’
rainbow-delimiters.el:55:5:Warning: reference to free variable ‘<script’
rainbow-delimiters.el:55:88:Warning: reference to free variable ‘></script>’
rainbow-delimiters.el:57:3:Warning: reference to free variable ‘<!’
rainbow-delimiters.el:63:3:Warning: reference to free variable ‘<script>’
rainbow-delimiters.el:64:3:Error: Invalid read syntax: "]"

then it appears as installed, but it is actually not.

**Comment by Fanael** [comment]
From the errors it looks like you somehow managed to get an HTML file downloaded instead, perhaps MELPA was acting up (@purcell?), try removing the package and installing it again.

**Comment by purcell** [comment]
No known problems on the MELPA side. Maybe check that your MELPA config is correct by comparing it to the README -- I see a lot of people using either the old melpa.milkbox.net URL, or not using HTTPS (only HTTPS is supported now).

**Comment by RedJocker** [comment]
thanks, it's working now.
