### ISSUE TITLE
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode) bug??

### ISSUE THREAD

**Issue by yyangdid** [Fanael/rainbow-delimiters#56]
when use `(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)` will break image.
example:

1. install `rainbow-delimiters`
``` emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :config
  (add-hook 'lisp-interaction-mode-hook #'rainbow-delimiters-mode)
  )
```
2. switch to `*scratch*` buffer, the major-mode is `lisp-interaction-mode`
3. insert `(insert-image (find-image '((:type png :file "splash.png"))))` and use `C-x C-e`, **a image will show**
4. if you change `(add-hook 'lisp-interaction-mode-hook #'rainbow-delimiters-mode)` to `(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)` , and restart emacs
5. switch to `*scratch*` buffer, the major-mode is `lisp-interaction-mode`
6. insert `(insert-image (find-image '((:type png :file "splash.png"))))` and use `C-x C-e`, **the image break, don't show**

in other prog-mode, like emacs-lisp , lisp-mode, c-mode, get the same thing, the image don't show.

is a bug?

**Comment by Fanael** [comment]
I cannot reproduce the problem locally, either with my usual config or under `emacs -Q`. Does the problem occur for you if you use a minimal configuration file that only sets up `rainbow-delimiters` and nothing else? If not, it's likely a different package that breaks image display, with `rainbow-delimiters` only being caught in the crossfire.

**Comment by yyangdid** [comment]
Ok, thanks. I will check other packages.
