### ISSUE TITLE
How to enable rainbow-delimiters in eval-expression minibuffer?

### ISSUE THREAD

**Issue by pyfx** [Fanael/rainbow-delimiters#57]
I have added this to my `~/.emacs`:

```elisp
(add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)
(add-hook 'eval-expression-minibuffer-setup-hook 'rainbow-delimiters-mode)
```

But when I enter the minibuffer with `M-:` and type `(((`, I don't see rainbow delimiters. I do see rainbow delimiters in `*scratch*` buffer so that proves that rainbow-delimiters is installed correctly. It is only in the eval-expression minibuffer where I am unable to get rainbow delimiters working.

Is there a way to get rainbow-delimiters working in the eval-expression minibuffer?

**Comment by Fanael** [comment]
`rainbow-delimiters` requires `font-lock-mode` to be enabled, and I'm not sure if that's possible in the eval-expression minibuffer.
