### ISSUE TITLE
Changing the font size for the currently matched delimiters

### ISSUE THREAD

**Issue by metatron-the-chronicler** [Fanael/rainbow-delimiters#60]
How can I configure rainbow-delimiters so that the currently matched are bigger than any other set of matched delimiters in addition to being highlighted?

**Comment by Fanael** [comment]
What do you mean by "currently matched"? The delimiter under point and its matching one? That's handled by `show-paren-mode`, not rainbow-delimiters.

**Comment by metatron-the-chronicler** [comment]
I mean the green (In my case) highlight for the current sexp.
![screen-sample](https://user-images.githubusercontent.com/2990993/121092424-88077780-c7b9-11eb-950a-164c2e5fbb8c.png)
Instead of it just being green I would like to make the parenthesis bigger when it is highlighted.

**Comment by Fanael** [comment]
It's not something that can be achieved with just rainbow-delimiters: it does not know or care where the point is, so it has no notion of "current sexp". It's some other package highlighting the current sexp for you.

At any rate, it's likely just a matter of setting the [`:height` attribute](https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html) of the appropriate face.
