### ISSUE TITLE
How to customize the delimeters?

### ISSUE THREAD

**Issue by roiholtzman** [Fanael/rainbow-delimiters#61]
I am writing text with equations in org-mode, and using doom emacs.
When I use signs of, say greater-equal `>`, I get a missed parenthesis coloring for the entire text.
I would like to remove these delimiters from the list of delimiters rainbow looks at.
I tried to run `customize-group` but since I am using `doom` it is disabled.
How can I customized it?

**Comment by Fanael** [comment]
What constitutes a delimiter is controlled solely by the major mode's [syntax table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html). If a character not intended to be a delimiter is nonetheless marked as one by the major mode, that's a bug in that major mode: it confuses all parts of emacs that rely on `parse-partial-sexp` and similar functions, not just rainbow-delimiters.

**Comment by roiholtzman** [comment]
Thanks! It seems quite involved to try and change these. Is there a simple way to remove a delimiter from a specific mode, say org-mode?

**Comment by rickalex21** [comment]
I'm having the same problem with the ">" everything after it is an unmatched face.

**Comment by rickalex21** [comment]
UPDATE - I ended up not using them at all. Hopefully it will help someone else.
```lisp
(defun my-rainbow-delimiters-face (depth match loc)
  (unless (memq (char-after loc) '(?\< ?\>))
    (rainbow-delimiters-default-pick-face depth match loc)))

(setq rainbow-delimiters-pick-face-function #'my-rainbow-delimiters-face)
```

**Comment by roiholtzman** [comment]
@rickalex21 This solution does not work for me. I mean that I still see rainbow highlights for `<` and `>`. Is this working for you?

**Comment by rickalex21** [comment]
@roiholtzman  I'm not using that anymore. This works, sometimes it won't work
if you get too crazy with code in comments of org code blocks but for 95% of cases
it works. Put it in your `:confg` section of use-package rainbow-delimiters.

```lisp
(defun my-rainbow-delimiters-gt-fix ()
      ;; TODO: Ending ’)’ is not automatically added. Not a big deal for org mode.
      "Fix unmatched face after greater than symbol ’>’"
    (modify-syntax-entry ?\< "w")
    (modify-syntax-entry ?\> "w"))

  (add-hook 'text-mode-hook 'my-rainbow-delimiters-gt-fix)

```
Given this as an org source block:

```lisp
(> 1 10)
```
You will not see unmached red here.
