### ISSUE TITLE
Question/Feature: Ignore less then, more than symbols (<>).

### ISSUE THREAD

**Issue by BuddhiLW** [Fanael/rainbow-delimiters#66]
More often than not, when I'm using rainbow mode in org-files, the symbols <, >, mess up my file font locking. 

Is there a way to configure so that rainbow-mode does not try to match these, or ignore them?

**Comment by Fanael** [comment]
`rainbow-delimiters` intentionally has no logic that determines what characters *are* delimiters, that's provided by the major mode in the form of a [syntax table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html). If the major mode indicates that `<` and `>` are paired delimiters, even though that's not necessarily true, it's a bug in that major mode.

An alternative solution to fix it within `rainbow-delimiters` would be #1, but getting that PR into a remotely usable form is… difficult.

**Comment by roiholtzman** [comment]
Just making sure: at this point, there is no way to remove the delimiters `<` and `>` for `rainbow-delimiters` specifically, right?

**Comment by Fanael** [comment]
Right.
