### ISSUE TITLE
Rainbow delimiters for YAML

### ISSUE THREAD

**Issue by iensu** [Fanael/rainbow-delimiters#67]
I haven't looked into how feasible this is, but I think another very useful application of rainbow delimiters mode would for highlighting YAML file indentation depth. Do you think this is possible?

**Comment by Fanael** [comment]
It definitely is possible, and actually relatively easy ­— just go over each line in the region `font-lock` tells you to fontify, giving it a face according to the indentation level — but it's outside of the purview of `rainbow-delimiters`, it would need to be its own separate package.
