### ISSUE TITLE
Python Docstring breakes coloring (treesit)

### ISSUE THREAD

**Issue by OlMon** [Fanael/rainbow-delimiters#80]
Greetings,

Thanks a lot for this package!

I have an issue, I am not sure if this is a rainbow-delimiters problem or python-ts-mode problem..

Looking at this code everything works fine, and the parentheses before `self` and after `name` are highlighted.

```python
class MyClass:
    """Testing
    """
    
    def __init__(self, name):
        self.name = name
```

But changing the docstring to the following:

```python
class MyClass:
    """ 
    Testing
    """
    
    def __init__(self, name):
        self.name = name
```
Will break the highlighting of the parentheses (in the whole buffer). This seems to only be a problem with the python treesit mode python-ts-mode. It does not happen immediately, sometimes adding an additional newline after `Testing` will break it. I can not figure a 100% consistent way.

Is this a problem of rainbow-delimiter or maybe the new treesit mode?
Thanks for the help.

Cheers!

**Comment by Fanael** [comment]
`python-ts-mode` breaks Emacs syntax engine: in the provided reproducer, `(nth 3 (syntax-ppss))` is `t` at the opening parenthesis, indicating that it's within a string, when it's obviously not. Rainbow-delimiters relies on the major mode providing correct syntax tables and properties, so it's often the canary in the coal mine, but it's likely not the only piece of code broken by this bug.

**Comment by bestlem** [comment]
I have other code broken in formatted strings

```
sql = f"""SELECT cwd FROM xonsh_history 
                WHERE 
                  {search_column} LIKE ? 
                  AND cwd != ?
                  AND inp NOT LIKE '{shortcut} %'
                  AND inp NOT LIKE '{shortcut}c %'
                GROUP BY cwd ORDER BY count(*) DESC
                LIMIT 10"""
```

The {} seem to be the things affected the } at the end of {search_column} is marked as an error as are the () in count(*) 

The {} on {shortcut} is OK.

**Comment by OlMon** [comment]
Thank you a lot and sorry for the noise!
